# Generated by Django 4.0.3 on 2022-05-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='last',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=20),
        ),
    ]
