# Generated by Django 4.0.4 on 2022-06-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_result1_remove_contact_full_name_contact_mobilec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result1',
            old_name='n1',
            new_name='rzlt',
        ),
    ]
