# Generated by Django 4.0.3 on 2022-05-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='result1',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
    ]
