# Generated by Django 4.0.4 on 2022-06-02 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='result1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
