# Generated by Django 4.0.3 on 2022-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_result1_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result1',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
    ]
