# Generated by Django 4.0.4 on 2022-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_result1_created_at_result1_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='nbtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('nb', models.IntegerField(default='', max_length=25)),
            ],
        ),
    ]
