# Generated by Django 4.0.4 on 2022-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_nbtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbtest',
            name='nb',
            field=models.IntegerField(default=0),
        ),
    ]
