# Generated by Django 4.0.4 on 2022-06-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_nbtest_nb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nbtest',
        ),
    ]
